### ISSUE TITLE
demo 运行报错

### ISSUE THREAD

**Issue by Zackratos** [vitaviva/fragivity#1]
![](https://user-images.githubusercontent.com/21094835/105010064-3b273c80-5a76-11eb-9c02-04d3811ae9f7.png)

如图所示

**Comment by Zackratos** [comment]
![164EADB1-EFAF-44F4-80AE-6D3F1455F629](https://user-images.githubusercontent.com/21094835/105010168-58f4a180-5a76-11eb-8bae-354435604481.png)

**Comment by vitaviva** [comment]
sry，已修复，请更新代码
