### ISSUE TITLE
一些想法

### ISSUE THREAD

**Issue by Lv-zhaoyang** [vitaviva/fragivity#10]
fragment生命周期这块处理很棒！

原生的navigator replace不好，改成add Fragment 也不太方便，
有的界面跳转需要add方式，有的界面需要replace方式，
root Fragment也会发生变化(例如账号登录前后，root Fragment 就变了)

**Comment by vitaviva** [comment]
> 例如账号登录前后，root Fragment 就变了

这种case有两种做法：
1. 多Activity：登录前后的页面用不同Activity承载，登录成功后finish自一个Activity
2. 单Activity：先退出当前Fragment再打开新Fragment，即先pop再push：
```
navigator.pop
navigator.push(XXXFragment::class)
```

**Comment by Lv-zhaoyang** [comment]
好的，谢谢！
