### ISSUE TITLE
关于pushWithPop的支持

### ISSUE THREAD

**Issue by liukai2530533** [vitaviva/fragivity#15]
1.关于pushWithPop字面意思，能实现开启二级页面并关闭一级页面吗？ root的fragment能支持pushWithPop吗？
2.关于DeekLink的跳转 现在的逻辑是跳转到这个Fragment了 但是此Activity会默认加载它的root fragment ，这个root fragment可能不是我想要加载的。可以DeekLink跳转到的目的Fragment作为root吗？或者可选是否需要默认的root fragment

**Comment by vitaviva** [comment]
1. 在NavOptions里加选项如何，就没必要多加一个api了，例如：
```kotlin
navigator.push(DestinationFragment::class) {
     popSelf = true
}
```

2. 可以实现，目前可以临时处理一下：在Activity中手动根据URI选择不同的root加载

**Comment by liukai2530533** [comment]
navigator.push(DestinationFragment::class) {
     popSelf = true
}
这个有点急需啊，没有这个不方便

**Comment by vitaviva** [comment]
> navigator.push(DestinationFragment::class) {
> popSelf = true
> }
> 这个有点急需啊，没有这个不方便

收到，尽快支持哈
