### ISSUE TITLE
配合hilt使用闪退

### ISSUE THREAD

**Issue by jiqianwen** [vitaviva/fragivity#17]
![QQ截图20210302100246](https://user-images.githubusercontent.com/26268908/109585658-dd8b1300-7b3e-11eb-95b1-51daee9557db.png)
这么调用的
navigator.push {
            ARouter.getInstance().build(“xxxx”).navigation() as Fragment
        }

**Comment by vitaviva** [comment]
多谢反馈，对Hilt没有适配，近期修复

**Comment by jiqianwen** [comment]
> 多谢反馈，对Hilt没有适配，近期修复

要是能出个组件化项目使用的demo就好了~

**Comment by qdsfdhvh** [comment]
+1我也遇到了相同问题, hilt模板重写了getContext()，new MyNavHost的时候我觉得可能需要传入requireActivity()。
```java
  private volatile FragmentComponentManager componentManager;
  @Override
  public Context getContext() {
    return componentContext;
  }
```
