### ISSUE TITLE
求问，怎么配合组件化使用

### ISSUE THREAD

**Issue by jiqianwen** [vitaviva/fragivity#20]
在现有项目上进行改造，使用的阿里路由
navigator.push {
            ARouter.getInstance().build(“”).navigation() as Fragment
        }
这样可以启动一个fragment   但是其他属性就无法设置了，求解

**Comment by vitaviva** [comment]
Close了？已经有解决方案了是吗？

**Comment by jiqianwen** [comment]
> Close了？已经有解决方案了是吗？

已经解决了是我看错方法了，是可以用路由的，还有一个体验感的问题
navigator.push({
            enterAnim = R.anim.h_fragment_enter
            exitAnim = R.anim.h_fragment_pop_exit
            popEnterAnim = R.anim.h_fragment_pop_enter
            popExitAnim = R.anim.h_fragment_exit
            popSelf = true
        }) {
            ARouter.getInstance().build(routePath).with(bundle).navigation() as Fragment
        }
启动一个新页面并销毁当前页面的时候，总是会先销毁再启动，总是会看到第一个页面，有办法做到无感退出吗？比如A启动B，B启动C同时销毁B，目前总是B退出看到A之后才启动了C，感觉怪怪的

**Comment by vitaviva** [comment]
> > Close了？已经有解决方案了是吗？
> 
> 已经解决了是我看错方法了，是可以用路由的，还有一个体验感的问题
> navigator.push({
> enterAnim = R.anim.h_fragment_enter
> exitAnim = R.anim.h_fragment_pop_exit
> popEnterAnim = R.anim.h_fragment_pop_enter
> popExitAnim = R.anim.h_fragment_exit
> popSelf = true
> }) {
> ARouter.getInstance().build(routePath).with(bundle).navigation() as Fragment
> }
> 启动一个新页面并销毁当前页面的时候，总是会先销毁再启动，总是会看到第一个页面，有办法做到无感退出吗？比如A启动B，B启动C同时销毁B，目前总是B退出看到A之后才启动了C，感觉怪怪的

ok, optimize later

**Comment by jiqianwen** [comment]
> Close了？已经有解决方案了是吗？

还有一个疑问，组件化的时候调用popto() 但是目标Fragment是在另一个模块中，没办法获取到目标Fragment对象，这时候该怎么操作？或者该怎么获取当前栈里所有的Fragment的集合，我可以popTo到指定下标的Fragment

**Comment by vitaviva** [comment]
反射获取fragment的class信息然后popTo 如何？

**Comment by vitaviva** [comment]
v0.2.0 新增了对route支持，可以看一下对你是否有帮助

**Comment by jiqianwen** [comment]
> v0.2.0 新增了对route支持，可以看一下对你是否有帮助

已经更新最新版，看了下代码，现有项目改动有点大，原先是用阿里路由的，不能兼容。找时间项目开个分支搞了试试，昨天已经放在项目里试过，应该是可行的。

**Comment by jiqianwen** [comment]
> v0.2.0 新增了对route支持，可以看一下对你是否有帮助

再请教一下，如何判断当前已经只有一个fragment在栈中？我想拦截返回事件，如果是最后一个fragment就退到后台而不是直接杀掉app进程，现在的按了返回app直接被杀了

**Comment by vitaviva** [comment]
暂时可以先这样获取：`navigator.navController.backStack.size`

**Comment by jiqianwen** [comment]
> 暂时可以先这样获取：`navigator.navController.backStack.size`

有没有方法判断启动的fragment是否执行完毕？我现在重写fragment的onCreateAnimation方法并不会执行，因为我发现有些页面会卡顿，应该是启动动画还没执行完毕，做了其他操作导致的

**Comment by qdsfdhvh** [comment]
> > 暂时可以先这样获取：`navigator.navController.backStack.size`
> 
> 有没有方法判断启动的fragment是否执行完毕？我现在重写fragment的onCreateAnimation方法并不会执行，因为我发现有些页面会卡顿，应该是启动动画还没执行完毕，做了其他操作导致的

可以把耗时任务放入idleHandler，会在线程空闲的时候执行。
```kotlin
private handler = Handler(Looper.getMainLooper())
fun doOnIdle(runnable: Runnable) {
    when {
        Looper.myLooper() == Looper.getMainLooper() -> {
            Looper.myQueue().addIdleHandler {
                runnable.run()
                false
            }
        }
        Build.VERSION.SDK_INT >= Build.VERSION_CODES.M -> {
            Looper.getMainLooper().queue.addIdleHandler {
                runnable.run()
                false
            }
        }
        else -> {
            handler.post {
                Looper.myQueue().addIdleHandler {
                    runnable.run()
                    false
                }
            }
        }
    }
}

doOnIdle {
  // 耗时任务
}
```

**Comment by jiqianwen** [comment]
> > > 暂时可以先这样获取：`navigator.navController.backStack.size`
> > 
> > 
> > 有没有方法判断启动的fragment是否执行完毕？我现在重写fragment的onCreateAnimation方法并不会执行，因为我发现有些页面会卡顿，应该是启动动画还没执行完毕，做了其他操作导致的
> 
> 可以把耗时任务放入idleHandler，会在线程空闲的时候执行。
> 
> ```kotlin
> private handler = Handler(Looper.getMainLooper())
> fun doOnIdle(runnable: Runnable) {
>     when {
>         Looper.myLooper() == Looper.getMainLooper() -> {
>             Looper.myQueue().addIdleHandler {
>                 runnable.run()
>                 false
>             }
>         }
>         Build.VERSION.SDK_INT >= Build.VERSION_CODES.M -> {
>             Looper.getMainLooper().queue.addIdleHandler {
>                 runnable.run()
>                 false
>             }
>         }
>         else -> {
>             handler.post {
>                 Looper.myQueue().addIdleHandler {
>                     runnable.run()
>                     false
>                 }
>             }
>         }
>     }
> }
> 
> doOnIdle {
>   // 耗时任务
> }
> ```

好的  感谢

**Comment by vitaviva** [comment]
> > Close了？已经有解决方案了是吗？
> 
> 已经解决了是我看错方法了，是可以用路由的，还有一个体验感的问题
> navigator.push({
> enterAnim = R.anim.h_fragment_enter
> exitAnim = R.anim.h_fragment_pop_exit
> popEnterAnim = R.anim.h_fragment_pop_enter
> popExitAnim = R.anim.h_fragment_exit
> popSelf = true
> }) {
> ARouter.getInstance().build(routePath).with(bundle).navigation() as Fragment
> }
> 启动一个新页面并销毁当前页面的时候，总是会先销毁再启动，总是会看到第一个页面，有办法做到无感退出吗？比如A启动B，B启动C同时销毁B，目前总是B退出看到A之后才启动了C，感觉怪怪的

此问题已修复：v0.2.1

**Comment by showwiki** [comment]
建议此问题开放，以后关于组件化的问题，可以在这里提，哈哈
