### ISSUE TITLE
如果获取当前栈顶的fragment

### ISSUE THREAD

**Issue by zwonb** [vitaviva/fragivity#24]
如果获取当前栈顶的fragment

**Comment by vitaviva** [comment]
理论上当前运行中的就是栈顶。所以是在什么场景下需要获取栈顶fragment呢？ 比如使用Activity时，很少有需求获取栈顶Activity

**Comment by zwonb** [comment]
用第三方库，里面有个东西跟fragment是分离开的，能拿到activity，但是获取不到实际的fragment，只能拿到ReportFragment




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月17日(星期三) 下午3:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [vitaviva/fragivity] 如果获取当前栈顶的fragment (#24)





 
理论上当前运行中的就是栈顶。所以是在什么场景下需要获取栈顶fragment呢？ 比如使用Activity时，很少有需求获取栈顶Activity

**Comment by vitaviva** [comment]
ReportFragment的唯一child就是实际fragment
即 `childFragmentManager.fragments.first()`

**Comment by zwonb** [comment]
暂时想到一个其他的解决方案了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月17日(星期三) 下午3:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [vitaviva/fragivity] 如果获取当前栈顶的fragment (#24)





 
ReportFragment的唯一child就是实际fragment
 即 childFragmentManager.fragments.first()

**Comment by vitaviva** [comment]
问题解决，close
