### ISSUE TITLE
最低版本兼容问题

### ISSUE THREAD

**Issue by liukai2530533** [vitaviva/fragivity#25]
1.能否调整最低版本兼容。该库的最低版本为5.0 应该是为了sharedElements的过渡动画 只能在5.0以上使用，那么能不能支持4.0或4.4版本呢？ 写了sharedElements 但是低于5.0版本的 不使用动画 这样可以吗？ 我们的项最低版本是4.4的.

2.popSelf的动画不顺畅  能不能设置为启动新页面之后，当前页面默默关闭，而不是先关闭再开启 ，这样动画感觉有点奇怪

**Comment by vitaviva** [comment]
1. ok 试着适配一下4.4
2. 已经提过类似问题了，正在修复

**Comment by vitaviva** [comment]
popSelf的问题已修复: v0.2.1 @liukai2530533

**Comment by vitaviva** [comment]
刚发布最新版0.2.2， minsdk已经支持到了19。 @liukai2530533

**Comment by liukai2530533** [comment]
能不能像以前一样支持构造方法传参啊

**Comment by qdsfdhvh** [comment]
> 能不能像以前一样支持构造方法传参啊

抱歉，这功能新版被我改坏了，已经修复，后续会打包更新。

**Comment by vitaviva** [comment]
> 能不能像以前一样支持构造方法传参啊

fixed in 0.2.5 , try again please
