### ISSUE TITLE
0.2.1 popself之后启动新的Fragment，navController的回退栈没更新还是显示旧的

### ISSUE THREAD

**Issue by zwonb** [vitaviva/fragivity#31]
0.2.1 popself之后启动新的Fragment，navController的回退栈没更新还是显示旧的

**Comment by vitaviva** [comment]
0.2.3试了popself有效的，你试试呢

**Comment by zwonb** [comment]
BackPressFragment里面 `navigator.push(ToNextFragment::class) { popSelf = true }`
ToNextFragment里面 `navigator.push(CheckListFragment::class)`
CheckListFragment里面 `navigator.popTo(ToNextFragment::class)` 不成功

**Comment by vitaviva** [comment]
fixed in v0.2.4
