### ISSUE TITLE
0.2.4版本少了一个

### ISSUE THREAD

**Issue by lodgkk** [vitaviva/fragivity#33]
![image](https://user-images.githubusercontent.com/8840336/115340318-f787c000-a195-11eb-9458-2aa5933c7658.png)
好像找不到 navigator

**Comment by vitaviva** [comment]
是FragivityUtil中没有navigator吗？
看了下有的呀
![Screen Shot 2021-04-20 at 2 23 41 PM](https://user-images.githubusercontent.com/6120268/115347581-288ee180-a1e4-11eb-8b84-deb10629e75d.png)

**Comment by lodgkk** [comment]
看到了,navigator这个只能在fragment中用

**Comment by vitaviva** [comment]
是的，fragment的扩展属性，因为需要依赖fragment做一些事情
