### ISSUE TITLE
0.2.4构造方法传参的问题

### ISSUE THREAD

**Issue by liukai2530533** [vitaviva/fragivity#34]
之前的版本没问题 升级到0.2.4版本之后我发现通过构造方法传参会被保存下来 比如点击News列表进入详情 点击第一条News进入NewsDetail ，然后我退出页面  再点第二条News 但是获取到的id还是第一条的id  。
我之前是可以通过构造传参的 现在是不支持了吗？如果要改动那工程量好大

**Comment by vitaviva** [comment]
0.2.5中已修复，请再试一下 @liukai2530533
