### ISSUE TITLE
如何判断当前已经只有一个fragment在栈中？我想拦截返回事件

### ISSUE THREAD

**Issue by lodgkk** [vitaviva/fragivity#36]
navigator.navController.backStack.size,我刚刚试了,发现当只有一个fragment的时候,返回2,想问问还有其他方法可以获取到吗

**Comment by vitaviva** [comment]
backStack中除了fragment以外还多一个NavGraph，所以size数会多1，可以做减1处理一下。暂时没有其他方法

**Comment by qdsfdhvh** [comment]
只是返回的话，可以用onBackPressedDispatcher。
see： https://github.com/vitaviva/fragivity/commit/eeb728e66a7f789bb49d642dcae59785ae3ba218
