### ISSUE TITLE
想返回多个fragment用什么方法呢

### ISSUE THREAD

**Issue by lodgkk** [vitaviva/fragivity#37]
有这么个需求,比如说微信登录需要绑定手机,首先到登录界面,然后获取信息之后到手机绑定页面,在这个手机绑定页面,我需要返回到微信登录之前的页面,用什么方法呢,因为之前微信登录之前的页面是首页

**Comment by lodgkk** [comment]
我用的是阿里路由,我试过好多方法了,
navigator.popTo(getARouterFragment(MainConstant.FRAG_MAIN).javaClass.kotlin)
返回错误No package ID 0e found for ID 0x0ecdd6f0.

fun getARouterFragment(url:String) :Fragment{
    return ARouter.getInstance().build(url).navigation() as Fragment
}

**Comment by lodgkk** [comment]
with(navHostFragment){
            composable("login"){ getARouterFragment(UserConstant.FRAG_LOGIN) }
        }
我在MainActivity里面这么处理了
在别的fragment里面执行navigator.popTo("login")
页面没有任何响应

**Comment by vitaviva** [comment]
> with(navHostFragment){
> composable("login"){ getARouterFragment(UserConstant.FRAG_LOGIN) }
> }
> 我在MainActivity里面这么处理了
> 在别的fragment里面执行navigator.popTo("login")
> 页面没有任何响应

@qdsfdhvh 这个问题能不能帮忙瞅一下？

**Comment by lodgkk** [comment]
log日志也没有打印

**Comment by qdsfdhvh** [comment]
> log日志也没有打印

方便整理出一个简单的demo吗，晚上我看下

**Comment by lodgkk** [comment]
有qq或者微信把,我把项目打包一下给你

**Comment by qdsfdhvh** [comment]
> 有qq或者微信把,我把项目打包一下给你 @qdsfdhvh

好的，微信：seiko_des
