### ISSUE TITLE
Add fragment 性能问题

### ISSUE THREAD

**Issue by pokercc** [vitaviva/fragivity#4]
使用add fragment 的方式添加fragment ,会存在一个问题，就是activity 在后台被系统回收，然后用户从任务管理器切换到这个activity时，回退栈里所有的fragment 都会执行onCreateView,会有比较严重的性能问题。

使用横竖屏切换demo，从日志上也可以得到验证
![image](https://user-images.githubusercontent.com/17515825/105146537-1648cd00-5b3b-11eb-8e64-bff87672d6d2.png)

**Comment by vitaviva** [comment]
好问题。特别是当回退栈上页面过多的话， 恢复重建会比较吃力。后续会做优化，多谢指教~
