### ISSUE TITLE
可以使用高版本的Fragment吗？

### ISSUE THREAD

**Issue by bozaixing** [vitaviva/fragivity#41]
“高版本Fragment，当同时应用Transition和applySlideIn时动画失效(原因待调查)，暂时降到1.3.0-alpha07”，这个问题修复了吗？

**Comment by qdsfdhvh** [comment]
之前调试下来是发现高版本FragmentManager使用新的State管理后，没走shared element相关代码；
如果你没用到shared element的话可以直接升级；用的少的话，也可以临时配置下:
```kotlin
FragmentManager.enableNewStateManager(false)
```

**Comment by bozaixing** [comment]
了解，谢谢大佬的及时回复。

**Comment by bozaixing** [comment]
FragmentManager.enableNewStateManager(false)， 这段代码加载哪个位置呢?

**Comment by qdsfdhvh** [comment]
> FragmentManager.enableNewStateManager(false)， 这段代码加载哪个位置呢?

这方法就改了个全局变量，只要在使用前配置就行了，不用了还可以改回来。

**Comment by bozaixing** [comment]
好的，谢谢了。
