### ISSUE TITLE
请教此框架Fragment碎片里面懒加载数据问题

### ISSUE THREAD

**Issue by bozaixing** [vitaviva/fragivity#42]
大佬，这个框架的懒加载数据的时机可不可以跟AndroidX一样放在onResume()生命周期方法里面加载呢，有没有具体的例子参考下呢？

**Comment by qdsfdhvh** [comment]
可以啊，本身就是基于navigation的，库里只是把切换时走onCreateView/onDestroyView的state减到了onStart/onStop。
懒加载的话，放idlehandler也是个不错的选择，https://github.com/vitaviva/fragivity/issues/20#issuecomment-801721449

**Comment by bozaixing** [comment]
非常感谢。大佬可以加个联系方式吗？

**Comment by qdsfdhvh** [comment]
> 非常感谢。大佬可以加个联系方式吗？
vx: seiko_des

**Comment by bozaixing** [comment]
收到，非常感谢。
