### ISSUE TITLE
[Deep Links]handleDeepLink添加NavOptions

### ISSUE THREAD

**Issue by Lv-zhaoyang** [vitaviva/fragivity#53]
你好，又来打扰了。

使用Deep Links  handleDeepLink跳转时，无法使用NavOptions里的启动模式等功能，
希望能添加这个功能，增强Deep Links，相当于简易版本的ARouter了 :smile:

**Comment by qdsfdhvh** [comment]
我个人还是建议一开始就使用主流路由框架；路由这个东西一旦确定不太好替换，fa库里应该不会有太完善的路由功能，毕竟能力和时间有限了；
还有路由框架方面我觉得美团的WMRouter比ARouter好些，推荐一些。

**Comment by Lv-zhaoyang** [comment]
> 我个人还是建议一开始就使用主流路由框架；路由这个东西一旦确定不太好替换，fa库里应该不会有太完善的路由功能，毕竟能力和时间有限了；
> 还有路由框架方面我觉得美团的WMRouter比ARouter好些，推荐一下。

好的，谢谢推荐。
