### ISSUE TITLE
关于popSelf跳转界面和替换根布局的问题

### ISSUE THREAD

**Issue by Fomovet** [vitaviva/fragivity#55]
1、使用popSelf跳转界面后使用手机物理键还能返回上一级
`Fragivity.of(this).pushTo(LoginFragment.class, new NavOptionsBuilder().popSelf(true).build());`

2、如何替换根布局？比如说A界面是根布局，从A界面跳转到B界面，此时B界面操作退出登录，那么跳转到登录界面C，这时候如何清掉A界面和B界面并且把C界面设为根布局？因为退出登录后就不能再返回主界面了此时栈列应该只有C界面一个Fragment

**Comment by qdsfdhvh** [comment]
试试这个：
```gradle
implementation 'com.github.vitaviva.fragivity:core:559bc5b0d0'
```

**Comment by Fomovet** [comment]
测试已修复
