### ISSUE TITLE
loadRoot不能带参数吗？

### ISSUE THREAD

**Issue by caojing35** [vitaviva/fragivity#6]
首个Fragment就需要传参的，怎么带参数加载？

**Comment by vitaviva** [comment]
请升级v0.1.2，新增了基于factory的loadRoot方法

**Comment by caojing35** [comment]
> 请升级v0.1.2，新增了基于factory的loadRoot方法

升级到0.1.3了，看到loadRoot增加了lambda方式的factory，但是我看了下实现，是根据class类型放在了一个Provider里，这种方式没法用可变的参数创建，能否补充提供？

**Comment by vitaviva** [comment]
>这种方式没法用可变的参数创建，能否补充提供？

是指构建fragment的时候传参吗? 现在可以传参，如下：
` navHostFragment.loadRoot { HomeFragment(xxx) }`

**Comment by caojing35** [comment]
Hello，用最新的库试了下，发现这里factory给Fragment传入的argument参数会在ReportFragment里onAttach的时候被覆盖成这个bundle
Bundle[{real=com.github.fragivity.example.HomeFragment}]
相关代码：           
`    override fun onAttach(context: Context) {
        super.onAttach(context)
        mChildFragmentManager.beginTransaction().apply {
            **_realFragment.arguments = arguments**
            add(R.id.container, _realFragment)
`

**Comment by caojing35** [comment]
还有个疑问，帮忙支持一下，factory方式的block入参noinline block: () -> T，Java侧不好调用，帮忙支持一下~

**Comment by vitaviva** [comment]
> Hello，用最新的库试了下，发现这里factory给Fragment传入的argument参数会在ReportFragment里onAttach的时候被覆盖成这个bundle
> Bundle[{real=com.github.fragivity.example.HomeFragment}]
> 相关代码：
> `
> 
> ```
> override fun onAttach(context: Context) {
> 
>     super.onAttach(context)
> 
>     mChildFragmentManager.beginTransaction().apply {
> 
>         _realFragment.arguments = arguments
> 
>         add(R.id.container, _realFragment)
> ```
> 
> `

Thank you for report。 fixed in  https://github.com/vitaviva/fragivity/issues/11

**Comment by caojing35** [comment]
> > Hello，用最新的库试了下，发现这里factory给Fragment传入的argument参数会在ReportFragment里onAttach的时候被覆盖成这个bundle
> > Bundle[{real=com.github.fragivity.example.HomeFragment}]
> > 相关代码：
> > `
> > ```
> > override fun onAttach(context: Context) {
> > 
> >     super.onAttach(context)
> > 
> >     mChildFragmentManager.beginTransaction().apply {
> > 
> >         _realFragment.arguments = arguments
> > 
> >         add(R.id.container, _realFragment)
> > ```
> > 
> > 
> > `
> 
> Thank you for report。 fixed in #11

多谢~ 顺便问一下，现在阶段发布release的节奏是什么想法？

**Comment by vitaviva** [comment]
> 多谢~ 顺便问一下，现在阶段发布release的节奏是什么想法？

对于重要的issue解决后会第一时间发版， 小的commit可能会多个汇总一起发版，争取至少每周都有更新吧

**Comment by vitaviva** [comment]
> 还有个疑问，factory方式的loadRoot，从Java侧似乎没法调用，能不能帮忙支持一下。

好的，会对Java侧的使用做一些兼容

**Comment by vitaviva** [comment]
> 还有个疑问，factory方式的loadRoot，从Java侧似乎没法调用，能不能帮忙支持一下。

0.1.5增加了一些Java侧的API，欢迎review，如果有什么修改或者补充，欢迎PR~
